# Generated by Django 3.0.2 on 2020-07-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('Course_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=50, unique=True)),
                ('Faculty', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=50)),
                ('Fee', models.FloatField()),
                ('Duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stud_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Student_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('Contactno', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
